package model;

public enum AchievementType {
    PLAYED_5_VIRTUAL_CONTESTS,
    PLAYED_10_VIRTUAL_CONTESTS,
    WON_1_VIRTUAL_CONTEST,
    WON_5_VIRTUAL_CONTESTS,
    WON_10_VIRTUAL_CONTESTS,
    FP_500_VIRTUAL_CONTEST,
    FP_700_VIRTUAL_CONTEST,
    FP_1000_VIRTUAL_CONTEST,
    DIFF_FP_100_VIRTUAL_CONTEST,
    DIFF_FP_200_VIRTUAL_CONTEST,
    DIFF_FP_300_VIRTUAL_CONTEST,

    PLAYED_5_OFFICIAL_CONTESTS,
    PLAYED_10_OFFICIAL_CONTESTS,
    WON_1_OFFICIAL_CONTEST,
    WON_5_OFFICIAL_CONTESTS,
    WON_10_OFFICIAL_CONTESTS,
    FP_500_OFFICIAL_CONTEST,
    FP_700_OFFICIAL_CONTEST,
    FP_1000_OFFICIAL_CONTEST,
    DIFF_FP_100_OFFICIAL_CONTEST,
    DIFF_FP_200_OFFICIAL_CONTEST,
    DIFF_FP_300_OFFICIAL_CONTEST,

    MANAGER_LEVEL_3,
    MANAGER_LEVEL_4,
    MANAGER_LEVEL_5,

    TRUE_SKILL_500,
    TRUE_SKILL_600,
    TRUE_SKILL_700,

    SOCCER_PLAYER_WON_FP_100,
    SOCCER_PLAYER_WON_FP_200,

    ALL_SOCCER_PLAYERS_WITH_FP,
}
