package model;

public enum AchievementType {
    PLAYED_5_VIRTUAL_CONTESTS,
    PLAYED_10_VIRTUAL_CONTESTS,
    WON_1_VIRTUAL_CONTEST,
    WON_5_VIRTUAL_CONTESTS,
    WON_10_VIRTUAL_CONTESTS,

    PLAYED_5_OFFICIAL_CONTESTS,
    PLAYED_10_OFFICIAL_CONTESTS,
    WON_1_OFFICIAL_CONTEST,
    WON_5_OFFICIAL_CONTESTS,
    WON_10_OFFICIAL_CONTESTS,
}
