/**
 * This class is generated by jOOQ
 */
package model.sql.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Optaxml extends org.jooq.impl.TableImpl<model.sql.tables.records.OptaxmlRecord> {

	private static final long serialVersionUID = -1621708472;

	/**
	 * The reference instance of <code>public.optaxml</code>
	 */
	public static final model.sql.tables.Optaxml OPTAXML = new model.sql.tables.Optaxml();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<model.sql.tables.records.OptaxmlRecord> getRecordType() {
		return model.sql.tables.records.OptaxmlRecord.class;
	}

	/**
	 * The column <code>public.optaxml.id</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>public.optaxml.xml</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.String> XML = createField("xml", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.optaxml.headers</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.String> HEADERS = createField("headers", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.optaxml.created_at</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.sql.Timestamp> CREATED_AT = createField("created_at", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * The column <code>public.optaxml.name</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.optaxml.feed_type</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.String> FEED_TYPE = createField("feed_type", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.optaxml.game_id</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.String> GAME_ID = createField("game_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.optaxml.competition_id</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.String> COMPETITION_ID = createField("competition_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.optaxml.season_id</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.lang.String> SEASON_ID = createField("season_id", org.jooq.impl.SQLDataType.CLOB, this, "");

	/**
	 * The column <code>public.optaxml.last_updated</code>.
	 */
	public final org.jooq.TableField<model.sql.tables.records.OptaxmlRecord, java.sql.Timestamp> LAST_UPDATED = createField("last_updated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

	/**
	 * Create a <code>public.optaxml</code> table reference
	 */
	public Optaxml() {
		this("optaxml", null);
	}

	/**
	 * Create an aliased <code>public.optaxml</code> table reference
	 */
	public Optaxml(java.lang.String alias) {
		this(alias, model.sql.tables.Optaxml.OPTAXML);
	}

	private Optaxml(java.lang.String alias, org.jooq.Table<model.sql.tables.records.OptaxmlRecord> aliased) {
		this(alias, aliased, null);
	}

	private Optaxml(java.lang.String alias, org.jooq.Table<model.sql.tables.records.OptaxmlRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, model.sql.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<model.sql.tables.records.OptaxmlRecord, java.lang.Integer> getIdentity() {
		return model.sql.Keys.IDENTITY_OPTAXML;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<model.sql.tables.records.OptaxmlRecord> getPrimaryKey() {
		return model.sql.Keys.OPTAXML_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<model.sql.tables.records.OptaxmlRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<model.sql.tables.records.OptaxmlRecord>>asList(model.sql.Keys.OPTAXML_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public model.sql.tables.Optaxml as(java.lang.String alias) {
		return new model.sql.tables.Optaxml(alias, this);
	}

	/**
	 * Rename this table
	 */
	public model.sql.tables.Optaxml rename(java.lang.String name) {
		return new model.sql.tables.Optaxml(name, null);
	}
}
