/**
 * This class is generated by jOOQ
 */
package model.sql;

/**
 * Convenience access to all sequences in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

	/**
	 * The sequence <code>public.optaxml_id_seq</code>
	 */
	public static final org.jooq.Sequence<java.lang.Long> OPTAXML_ID_SEQ = new org.jooq.impl.SequenceImpl<java.lang.Long>("optaxml_id_seq", model.sql.Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
