/**
 * This class is generated by jOOQ
 */
package model.sql;

/**
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.optaxml
	 */
	public static final model.sql.tables.Optaxml OPTAXML = model.sql.tables.Optaxml.OPTAXML;
}
