/**
 * This class is generated by jOOQ
 */
package model.sql.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.0"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OptaxmlRecord extends org.jooq.impl.UpdatableRecordImpl<model.sql.tables.records.OptaxmlRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -536618467;

	/**
	 * Setter for <code>public.optaxml.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.optaxml.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>public.optaxml.xml</code>.
	 */
	public void setXml(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.optaxml.xml</code>.
	 */
	public java.lang.String getXml() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.optaxml.headers</code>.
	 */
	public void setHeaders(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.optaxml.headers</code>.
	 */
	public java.lang.String getHeaders() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.optaxml.created_at</code>.
	 */
	public void setCreatedAt(java.sql.Timestamp value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.optaxml.created_at</code>.
	 */
	public java.sql.Timestamp getCreatedAt() {
		return (java.sql.Timestamp) getValue(3);
	}

	/**
	 * Setter for <code>public.optaxml.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.optaxml.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.optaxml.feed_type</code>.
	 */
	public void setFeedType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.optaxml.feed_type</code>.
	 */
	public java.lang.String getFeedType() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.optaxml.game_id</code>.
	 */
	public void setGameId(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.optaxml.game_id</code>.
	 */
	public java.lang.String getGameId() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.optaxml.competition_id</code>.
	 */
	public void setCompetitionId(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.optaxml.competition_id</code>.
	 */
	public java.lang.String getCompetitionId() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>public.optaxml.season_id</code>.
	 */
	public void setSeasonId(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.optaxml.season_id</code>.
	 */
	public java.lang.String getSeasonId() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>public.optaxml.last_updated</code>.
	 */
	public void setLastUpdated(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.optaxml.last_updated</code>.
	 */
	public java.sql.Timestamp getLastUpdated() {
		return (java.sql.Timestamp) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.sql.Timestamp, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return model.sql.tables.Optaxml.OPTAXML.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return model.sql.tables.Optaxml.OPTAXML.XML;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return model.sql.tables.Optaxml.OPTAXML.HEADERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field4() {
		return model.sql.tables.Optaxml.OPTAXML.CREATED_AT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return model.sql.tables.Optaxml.OPTAXML.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return model.sql.tables.Optaxml.OPTAXML.FEED_TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return model.sql.tables.Optaxml.OPTAXML.GAME_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return model.sql.tables.Optaxml.OPTAXML.COMPETITION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return model.sql.tables.Optaxml.OPTAXML.SEASON_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return model.sql.tables.Optaxml.OPTAXML.LAST_UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getXml();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getHeaders();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value4() {
		return getCreatedAt();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getFeedType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getGameId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCompetitionId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getSeasonId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getLastUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value2(java.lang.String value) {
		setXml(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value3(java.lang.String value) {
		setHeaders(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value4(java.sql.Timestamp value) {
		setCreatedAt(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value5(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value6(java.lang.String value) {
		setFeedType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value7(java.lang.String value) {
		setGameId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value8(java.lang.String value) {
		setCompetitionId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value9(java.lang.String value) {
		setSeasonId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord value10(java.sql.Timestamp value) {
		setLastUpdated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public OptaxmlRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.String value3, java.sql.Timestamp value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.String value8, java.lang.String value9, java.sql.Timestamp value10) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached OptaxmlRecord
	 */
	public OptaxmlRecord() {
		super(model.sql.tables.Optaxml.OPTAXML);
	}

	/**
	 * Create a detached, initialised OptaxmlRecord
	 */
	public OptaxmlRecord(java.lang.Integer id, java.lang.String xml, java.lang.String headers, java.sql.Timestamp createdAt, java.lang.String name, java.lang.String feedType, java.lang.String gameId, java.lang.String competitionId, java.lang.String seasonId, java.sql.Timestamp lastUpdated) {
		super(model.sql.tables.Optaxml.OPTAXML);

		setValue(0, id);
		setValue(1, xml);
		setValue(2, headers);
		setValue(3, createdAt);
		setValue(4, name);
		setValue(5, feedType);
		setValue(6, gameId);
		setValue(7, competitionId);
		setValue(8, seasonId);
		setValue(9, lastUpdated);
	}
}
